### ISSUE TITLE
Missing metanorma-mpfd gem for docker CI

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn-samples-mpfa#20]
https://github.com/metanorma/mn-samples-mpfa/actions/runs/67384321

for some reason `bundle install` install gem from `Gemfile` which embedded in the container

To be investigated

**Comment by CAMOBAP** [comment]
We had this issue before but it was "muted" https://github.com/metanorma/mn-samples-mpfa/runs/523353675?check_suite_focus=true

**Comment by ronaldtse** [comment]
The container is also missing `yq`, we should better supply it in the container for now.

**Comment by CAMOBAP** [comment]
@ronaldtse actually missing `yq` fixed in last run https://github.com/metanorma/mn-samples-mpfa/actions/runs/67384321, the only missing gem issue left

**Comment by CAMOBAP** [comment]
Investigation results:
 - Both `bundle exec cat Gemfile` and `cat Gemfile` show correct `Gemfile` (host one)
 - `bundle install` still use `Gemfile` from container
 - `gem install metanorma-mpfd` finish successfully but doesn't help at all
 - `bundle list` also report gems from container's `Gemfile`
 - `bundle add metranorma-mpfd; bundle install` will do the trick but I think we need a more reliable solution

To be continued....

**Comment by ronaldtse** [comment]
@CAMOBAP you can use this:
```
BUNDLE_GEMFILE=my.gemfile bundle
```

To use a specific Gemfile.

**Comment by CAMOBAP** [comment]
@ronaldtse 

`BUNDLE_GEMFILE=my.gemfile bundle` lead to the error below for some reason

> /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/resolver.rb:290:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'metanorma-mpfd' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)

Also, I tried `bundle install --gemfile=./Gemfile` and looks like it works but next call of `metanorma` (I did both in the same docker session) return

> [metanorma] Error: loading gem `metanorma-mpfd` failed. Exiting.

Looks like installation happens to another directory

Generally, event if the problem will be solved we will need to install `metanorma-mpfa` on each `docker run ...` call

So even if we will add this `env METANORMA_DOCKER=metanorma/mn make clean all publish` becomes less usable for such repositories which require an extra gem

Docker still can be used with next command `docker run -v "$(pwd)":/metanorma metanorma/mn bash -c "bundle add metanorma-mpfd; make clean all publish"`

So generally I'm questioning the need of `env METANORMA_DOCKER=metanorma/mn make clean all publish` usecase

**Comment by ronaldtse** [comment]
`env METANORMA_DOCKER=metanorma/mn make clean all publish` is just a mechanism used to invoke compilation, we could change it.
