### ISSUE TITLE
Convert parts of Guidelines

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-mpfa#3]
* http://www.mpfa.org.hk/eng/legislation_regulations/legulations_ordinance/guidelines/current_version/licensing/files/I_1.pdf
* http://www.mpfa.org.hk/eng/legislation_regulations/legulations_ordinance/guidelines/current_version/licensing/files/I_2.pdf
* http://www.mpfa.org.hk/eng/legislation_regulations/legulations_ordinance/guidelines/current_version/licensing/files/I_3_e.pdf

**Comment by opoudjis** [comment]
Did not see this, have ended up doing  http://www.mpfa.org.hk/eng/legislation_regulations/legulations_ordinance/guidelines/current_version/orso_interface/files/V_2.pdf

**Comment by ronaldtse** [comment]
For the Guidelines, seems that each document is a separate one because they are versioned independently (http://www.mpfa.org.hk/eng/legislation_regulations/legulations_ordinance/guidelines/previous_versions/index.jsp).

I wonder how it is best presented:

* independent documents?
* single Guidelines document?
* both?

**Comment by opoudjis** [comment]
Clearly independent documents: they are being managed differently, and it would be madness to try and merge them into one über document, even with includes.

**Comment by ronaldtse** [comment]
I agree that they are independent but their interface makes it very hard to navigate the full set of guidelines. The original intention was one unified document will make it much easier to navigate.

Any ideas on how to improve navigation/readability of a large document (almost like a document sytsem) like this? We're having this problem with some large internal documents, too.

**Comment by opoudjis** [comment]
*Navigation* is a solved problem, but the solution lies in the HTML hyperlinking of components, and good use of breadcrumbs and sidebars. That is an HTML presentation challenge, not one that is in scope of Metanorma: it's how you organise the outputs of Metanorma. 

In fact, having one big document as Metanorma output, with internal anchors for navigation, is going to be a nightmare, both for responsiveness and just for navigation. Separate documents in HTML, with an omnipresent and unchanging navigation bar and breadcrumbs, is the only sustainable way to navigate a big document.

If their interface doesn't enable that, the solution is to for them to build a better interface. But this is not a Metanorma problem, it's a UI problem.

**Comment by ronaldtse** [comment]
Good call. Good cross referencing is the issue here. That said...

We have an internal document hundreds of pages long, all mashed into one, but could actually be split into dozens of individual ones. It's a UI issue we have to solve internally -- can Metanorma help fix this with better navigation?

i.e. How to produce a unified UI for multiple Metanorma documents of the same level? One Meta Metanorma document? 😉

**Comment by opoudjis** [comment]
This sounds like simply a file manifest, listing file names and sequence, which gets fed into an html engine. I don't see the need to overengineer this.
