### ISSUE TITLE
Malformed Output XML for html: 1180:53: FATAL: Double hyphen within comment

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn-samples-mpfa#37]
https://github.com/metanorma/mn-samples-mpfa/actions/runs/118418468

echo "Running locally..."; bundle exec metanorma documents/mpfd-bpn.xml
Running locally...
nil versions are discouraged and will be deprecated in Rubygems 4
Malformed Output XML for html: 1180:53: FATAL: Double hyphen within comment: <!--
  <div class="document-stage-band" id="published- (see documents/mpfd-bpn.html.err)
make: *** [documents/mpfd-bpn.html] Error 1

**Comment by opoudjis** [comment]
Issue has gone away
