### ISSUE TITLE
There aren't .doc files

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-samples-mpfa#50]
Build process  in mn-native-pdf failed https://github.com/metanorma/mn-native-pdf/runs/2045780416?check_suite_focus=true due it can't find file `documents/mpfa-bpn.doc` :
````
make: *** No rule to make target 'documents/mpfa-bpn.doc', needed by 'documents.rxl'.  Stop.
````

Before:
![изображение](https://user-images.githubusercontent.com/5559926/110203767-07b33c80-7e81-11eb-908a-00f35e956a69.png)

Now:
![изображение](https://user-images.githubusercontent.com/5559926/110203784-1699ef00-7e81-11eb-9b3d-b503ad6ee151.png)

**Comment by ronaldtse** [comment]
@CAMOBAP perhaps this is due to mpfa-bpn.adoc missing doc in this line:
```
:mn-output-extensions: xml,pdf,html,rxl
```

**Comment by ronaldtse** [comment]
Fixed.

**Comment by Intelligent2013** [comment]
@ronaldtse thank you.
