### ISSUE TITLE
Adapt Relaton style of index documents for this repo

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-mpfa#6]
Refer to https://github.com/CalConnect/csd-vpoll/

**Comment by CAMOBAP** [comment]
@ronaldtse you mean this https://github.com/CalConnect/csd-vpoll/blob/master/metanorma.yml#L5 and logic which handle it?

**Comment by ronaldtse** [comment]
Yes indeed. Thank you!

**Comment by ronaldtse** [comment]
And move all source files inside `/sources/` folder.

**Comment by ronaldtse** [comment]
Done in 94157f0f03511ccc0017ff3049eb199e307828c8.
